[package]
name = "youtube-half-open-redirect-vuln"
version = "1.0"
authors = ["Marco S. <marcuccio.dev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]